### ISSUE TITLE
Broken Makefile - CS100 Grader 

### ISSUE THREAD

**Issue by lepatrick714** [jonathanwoolf/rshell#1]
Please review your makefile 

It does not create the ./bin directory thus will cause an error when running make. 
Lastly please clone your repo on the hammer server and run it to ensure that everything works

Thank you 
P.S. Email me at lle018@ucr.edu for any questions

**Comment by hdoan002** [comment]
I have fixed the make bin issue. Thank you for bringing the issue to our attention!
